# 03 ? Refer?ncias e compara??o de classificadores
Usamos os conjuntos por utilizador do notebook 02. A compara??o utiliza cinco folds de StratifiedGroupKFold **apenas no treino**, com os mesmos grupos e semente para todos os modelos. A Pipeline completa ? ajustada dentro de cada fold. A valida??o separada permite analisar a transfer?ncia para outros utilizadores.
O F1 de Suspicious ? o crit?rio principal; Average Precision ? secund?rio. Precision e Recall s?o interpretados com as contagens de erros. Quando n?o existem previs?es positivas, a Precision ? indefinida: o c?digo devolve zero por conven??o e assinala essa situa??o.
Os resultados iniciais usam a regra predict de cada algoritmo. A otimiza??o e um eventual ajuste de limiar ser?o feitos exclusivamente no desenvolvimento. O teste final n?o ? avaliado neste notebook.

In [1]:
from pathlib import Path
import sys
RAIZ = next(p for p in [Path.cwd(), *Path.cwd().parents] if (p / 'data/raw/cybercrime_forensic_dataset.csv').exists())
if str(RAIZ) not in sys.path:
    sys.path.insert(0, str(RAIZ))
from src.experiencias import executar_experiencia, tabela_resultados, guardar_resultados
resultados = []

## Refer?ncias simples
A refer?ncia maiorit?ria obt?m accuracy elevada sem detetar qualquer registo suspeito. Prever sempre Suspicious atinge recall total ? custa de sinalizar todos os registos normais. As pontua??es constantes produzem ROC-AUC de 0,5 e Average Precision igual ? preval?ncia positiva.
Estas regras s?o implementadas com DummyClassifier, usando as mesmas entradas e protocolo dos candidatos, para tornar expl?cito o que significa melhorar.

In [2]:
for nome in ["maioritaria", "sempre_suspeita"]:
    resultado = executar_experiencia(nome)
    resultados.append(resultado)
display(tabela_resultados(resultados).round(4))

,F1 CV,Desvio F1 CV,F1 treino,F1 validação,Precision,Recall,Accuracy,ROC-AUC,Average Precision,FP,FN
Modelo,,,,,,,,,,,
maioritaria,0.000,0.0000,0.000,0.0000,0.0000,0.0,0.8369,0.5,0.1631,0,241
sempre_suspeita,0.285,0.0007,0.285,0.2804,0.1631,1.0,0.1631,0.5,0.1631,1237,0

## Registo de resultados de desenvolvimento
O ficheiro pequeno seguinte cont?m m?tricas reais, n?o dados processados nem modelos. As refer?ncias e candidatos s?o avaliados apenas no desenvolvimento. A variabilidade dos folds ? descritiva e n?o constitui um intervalo de confian?a de incidentes independentes.

In [3]:
display(tabela_resultados(resultados).round(4))
guardar_resultados(resultados)
print("Resultados guardados em resultados/desenvolvimento.json; teste final n?o avaliado.")

,F1 CV,Desvio F1 CV,F1 treino,F1 validação,Precision,Recall,Accuracy,ROC-AUC,Average Precision,FP,FN
Modelo,,,,,,,,,,,
maioritaria,0.000,0.0000,0.000,0.0000,0.0000,0.0,0.8369,0.5,0.1631,0,241
sempre_suspeita,0.285,0.0007,0.285,0.2804,0.1631,1.0,0.1631,0.5,0.1631,1237,0

Resultados guardados em resultados/desenvolvimento.json; teste final n?o avaliado.